In [1]:
import pandas as pd
from tqdm.std import tqdm
from openai import OpenAI
import re
import os
import json

In [2]:
input_data = "input_files/semantic_matching_0099.csv"
output_data = "output_files/semantic_matching_0099.xlsx"

In [3]:
# ## Open AI API
# os.environ["OPENAI_API_KEY"] = "your open ai api"
from dotenv import load_dotenv

load_dotenv()

True

## common functions

In [4]:
def to_pascal_case(phrase):
    # Remove parentheses and the content inside them, e.g., (Unaudited)
    phrase = re.sub(r'\s*\([^)]*\)', '', phrase)
    
    # Split on non-alphanumeric characters
    words = re.split(r'[^a-zA-Z0-9]', phrase)
    
    # Capitalize each word and join
    return ''.join(word.capitalize() for word in words if word)

In [5]:
def read_xml(xml_path):
    with open(xml_path, "r", encoding="utf-8") as f:
        content = f.read()

        return content

In [6]:
"""
    This function is different a bit among different tasks, here is for the semantic matching task
"""

def construct_annotation(df, results, task_name="semantic_matching"):
    """
        the options of task_name are semantic_matching, relationship_extraction, and mathematical_reasoning
    """
    new_df = df.copy(deep=True)

    schema = []
    presentation = []
    calculation = []
    definition = []
    label = []
    instance = []
    us_gaap = []
    true_answer = []
    segmentation_path = []
    parse_ok = []
    input = []
    outputByLLM = []
    
    for res in results:
        segmentation_name = res.get("segmentation_name")
        folder_name = res.get("folder_name")

        prefix_path = os.path.join(f"segmentation_filing/{task_name}", folder_name)
        real_segmentation_names = os.listdir(prefix_path)
        potential_seg_names = []

        ## obtain the potential segmentation folders using partial match
        for seg_name in real_segmentation_names:
            normalized_segmentation_name = segmentation_name.lower()
            normalized_seg_name = seg_name.lower()
            if (normalized_segmentation_name in normalized_seg_name) or (normalized_seg_name in normalized_segmentation_name):
                potential_seg_names.append(seg_name)
        
        parse = False
        cal = None
        pre = None
        defn = None
        lab = None
        ins = None
        sch = None
        seg_path = None
        answers = [tag.get("tag") for tag in res.get("error_tags")]
        for segmentation_name_ in potential_seg_names:
            
            full_path = os.path.join(prefix_path, segmentation_name_)
    
            temp_cal = None
            temp_pre = None
            temp_defn = None
            temp_lab = None
            temp_ins = None
            temp_sch = None
            
            file_list = os.listdir(full_path)
            
            for file_name in file_list:
                if file_name.endswith("cal.xml"):
                    final_path = os.path.join(full_path,file_name)
                    temp_cal = read_xml(final_path)
                elif file_name.endswith("pre.xml"):
                    final_path = os.path.join(full_path,file_name)
                    temp_pre = read_xml(final_path)
                elif file_name.endswith("def.xml"):
                    final_path = os.path.join(full_path,file_name)
                    temp_defn = read_xml(final_path)
                elif file_name.endswith("lab.xml"):
                    final_path = os.path.join(full_path,file_name)
                    temp_lab = read_xml(final_path)
                elif file_name.endswith("htm.xml"):
                    final_path = os.path.join(full_path,file_name)
                    temp_ins = read_xml(final_path)
                elif file_name.endswith("xsd"):
                    final_path = os.path.join(full_path,file_name)
                    temp_sch = read_xml(final_path)
                else:
                    continue

            is_appear = True
            for ans in answers:
                # check the presentation linkbase
                if ans in temp_pre:
                    continue
                elif ans.replace(":","") in temp_pre:
                    continue
                elif ans.replace(":","_") in temp_pre:
                    continue
                else:
                    is_appear = False
                    break
           
            if is_appear:
                parse = True
                cal = temp_cal
                pre = temp_pre
                defn = temp_defn
                lab = temp_lab
                ins = temp_ins
                sch = temp_sch
                seg_path = os.path.join(folder_name, segmentation_name_)
                break
        
        calculation.append(cal)
        presentation.append(pre)
        definition.append(defn)
        label.append(lab)
        instance.append(ins)
        schema.append(sch)
        true_answer.append(answers)
        us_gaap.append(None)
        parse_ok.append(parse)
        segmentation_path.append(seg_path)
        input.append(None)
        outputByLLM.append(res)
     
        
    new_df["schema"] = schema
    new_df["presentation"] = presentation
    new_df["calculation"] = calculation
    new_df["definition"] = definition
    new_df["label"] = label
    new_df["instance"] = instance
    new_df["us_gaap"] = us_gaap
    new_df["input"] = input
    new_df["true_answer"] = true_answer
    new_df["segmentation_path"] = segmentation_path
    new_df["parse_successful"] = parse_ok
    new_df["LLM_Output"] = outputByLLM

    return new_df

## load dqc messages for semantic matching task

In [7]:
sm_99_df = pd.read_csv(input_data)

In [8]:
sm_99_df

,assertion.code,assertion.detail,assertion.run-date,assertion.severity,assertion.source,assertion.type,entity.cik,entity.name,report.accepted-timestamp,report.accession,report.base-taxonomy,report.creation-software,report.document-type,report.entry-url,report.filing-date,report.filing-year,report.id,report.sec-url,report.sic-code,folder_name
0,DQC.US.0099.9533,"2022-01-03 11:15:38,239 [DQC.US.0099.9533] \nT...",2022-01-03,ERROR,DQC,99,1570132,"ANVI GLOBAL HOLDINGS, INC.",2022-01-03 10:40:00,0001553350-22-000002,US GAAP 2021,Field: Set; Name: xdx; ID: xdx_050_edei%2D%2DD...,10-Q,http://www.sec.gov/Archives/edgar/data/1570132...,2022-01-03,2022,409852,https://www.sec.gov/Archives/edgar/data/157013...,5400,10q-anvi-20211130
1,DQC.US.0099.9533,"2022-01-18 07:01:54,632 [DQC.US.0099.9533] \nT...",2022-01-18,ERROR,DQC,99,1796949,"GenFlat Holdings, Inc.",2022-01-18 06:02:00,0001654954-22-000549,US GAAP 2020,Document Created by XBRLMaster,10-Q,http://www.sec.gov/Archives/edgar/data/1796949...,2022-01-18,2022,412314,https://www.sec.gov/Archives/edgar/data/179694...,8742,10q-hbr-20211130
2,DQC.US.0099.9533,"2022-01-18 07:01:54,632 [DQC.US.0099.9533] \nT...",2022-01-18,ERROR,DQC,99,1796949,"GenFlat Holdings, Inc.",2022-01-18 06:02:00,0001654954-22-000549,US GAAP 2020,Document Created by XBRLMaster,10-Q,http://www.sec.gov/Archives/edgar/data/1796949...,2022-01-18,2022,412314,https://www.sec.gov/Archives/edgar/data/179694...,8742,10q-hbr-20211130
3,DQC.US.0099.9533,"2022-03-09 20:16:45,117 [DQC.US.0099.9533] \nT...",2022-03-10,ERROR,DQC,99,1304161,"PHARMA-BIO SERV, INC.",2022-02-11 17:21:00,0001654954-22-001532,US GAAP 2021,Document Created by XBRLMaster,10-K,http://www.sec.gov/Archives/edgar/data/1304161...,2022-02-11,2022,418188,https://www.sec.gov/Archives/edgar/data/130416...,8742,10k-pbsv-20211031
4,DQC.US.0099.9533,"2022-02-15 07:30:54,506 [DQC.US.0099.9533] \nT...",2022-02-15,ERROR,DQC,99,1620749,PANAMERA HOLDINGS CORPORATION,2022-02-14 21:51:00,0001640334-22-000315,US GAAP 2021,Document Created by XBRLMaster,10-K,http://www.sec.gov/Archives/edgar/data/1620749...,2022-02-15,2022,419692,https://www.sec.gov/Archives/edgar/data/162074...,8742,10k-pnht-20210731
5,DQC.US.0099.9533,"2022-02-15 07:30:54,507 [DQC.US.0099.9533] \nT...",2022-02-15,ERROR,DQC,99,1620749,PANAMERA HOLDINGS CORPORATION,2022-02-14 21:51:00,0001640334-22-000315,US GAAP 2021,Document Created by XBRLMaster,10-K,http://www.sec.gov/Archives/edgar/data/1620749...,2022-02-15,2022,419692,https://www.sec.gov/Archives/edgar/data/162074...,8742,10k-pnht-20210731
6,DQC.US.0099.9533,"2022-02-18 09:45:49,004 [DQC.US.0099.9533] \nT...",2022-02-18,ERROR,DQC,99,1602813,FRONTERA GROUP INC.,2022-02-18 09:24:00,0001549727-22-000009,US GAAP 2020,Field: Doc-Info; Name: Generator; Value: GoFil...,10-Q,http://www.sec.gov/Archives/edgar/data/1602813...,2022-02-18,2022,422094,https://www.sec.gov/Archives/edgar/data/160281...,8742,10q-frtg-20211231
7,DQC.US.0099.9533,"2022-12-19 12:02:34,485 [DQC.US.0099.9533] \nT...",2022-12-19,ERROR,DQC,99,1230524,"Leopard Energy, Inc.",2022-12-14 16:20:00,0001903596-22-000915,US GAAP 2021,Novaworks,10-Q,http://www.sec.gov/Archives/edgar/data/1230524...,2022-12-14,2022,535328,https://www.sec.gov/Archives/edgar/data/123052...,8742,10q-cetc-20221031
8,DQC.US.0099.9533,"2022-11-23 06:02:44,800 [DQC.US.0099.9533] \nT...",2022-11-23,ERROR,DQC,99,1602813,FRONTERA GROUP INC.,2022-11-22 15:10:00,0001549727-22-000096,US GAAP 2022,Novaworks,10-Q,http://www.sec.gov/Archives/edgar/data/1602813...,2022-11-22,2022,531482,https://www.sec.gov/Archives/edgar/data/160281...,8742,10q-frtg-20220930
9,DQC.US.0099.9533,"2022-11-17 06:28:43,249 [DQC.US.0099.9533] \nT...",2022-11-17,ERROR,DQC,99,1876945,Gold Flora Corporation,2022-11-14 16:56:00,0001654954-22-015300,US GAAP 2022,Document Created by XBRLMaster,10-Q,http://www.sec.gov/Archives/edgar/data/1876945...,2022-11-14,2022,529878,https://www.sec.gov/Archives/edgar/data/187694...,100,10q-gramf-20220930
10,DQC.US.0099.9533,"2022-11-17 06:28:43,249 [DQC.US.0099.9533] \nT...",2022-11-17,ERROR,DQC,99,1876945,Gold Flora Corporation,2022-11-14 16:56:00,0001654954-22-015300,US GAAP 2022,Document Created by XBRLMaster,10-Q,http://www.sec.gov/Archives/edgar/data/1876945...,2022-11-14,2022,529878,https://www.sec.gov/Archives/edgar/data/187694...,100,10q-gramf-20220930
11,DQC.US.0099.9533,"2022-11-17 06:28:43,249 [DQC.US.0099.9533] \nT...",2022-11-17,ERROR,DQC,99,1876945,Gold Flora Corporation,2022-11-14 16:56:00,0001654954-22-015300,US GAAP 2022,Document Created by XBRLMaster,10-Q,http://www.sec.gov/Archives/edgar/data/1876945...,2022-11-14,2022,529878,https://www.sec.gov/Archives/edgar/data/187694...,100,10q-gramf-20220930
12,DQC.US.0099.9533,"2022-11-15 07:58:34,662 [DQC.US.0099.9533] \nT...",2022-11-15,ERROR,DQC,99,1471781,GBT TECHNOLOGIES INC.,2022-11-14 16:17:00,0001731122-22-001969,US GAAP 2022,Field: Set; Name: xdx; ID: xdx_059_edei%2D%2DD...,10-Q,http://www.sec.gov/Archives/edgar/data/1471781...,2022-11-14,2022,528572,https://www.sec.gov/Archives/edgar/data/147178...,8742,10q-gtch-20220930
13,DQC.US.0099.9533,"2022-11-15 07:58:34,662 [DQC.US.0099.9533] \nT...",2022-11-15,ERROR,DQC,99,1471781,GBT TECHNOLOGIES INC.,2022-11-14 16:17:00,0001731122-22-001969,US GAAP 2022,Field: Set; Name: xdx; ID: xdx_059_edei%2D%2DD...,10-Q,http://www.sec.gov/Archives/edgar/data/1471781...,2022-11-14,2022,528572,https://www.sec.gov/Archives/edgar/data/147178...,8742,10q-gtch-20220930
14,DQC.US.0099.9533,"2022-11-15 07:58:34,662 [DQC.US.0099.9533] \nT...",2022-11-15,ERROR,DQC,99,1471781,GBT TECHNOLOGIES INC.,2022-11-14 16:17:00,0001731122-22-001969,US GAAP 2022,Field: Set; Name: xdx; ID: xdx_059_edei%2D%2DD...,10-Q,http://www.sec.gov/Archives/edgar/data/1471781...,2022-11-14,2022,528572,https://www.sec.gov/Archives/edgar/data/147178...,8742,10q-gtch-20220930
15,DQC.US.0099.9533,"2022-11-15 06:36:01,493 [DQC.US.0099.9533] \nT...",2022-11-15,ERROR,DQC,99,1641751,BrewBilt Manufacturing Inc.,2022-11-14 13:32:00,0001641751-22-000018,US GAAP 2022,Field: Set; Name: xdx; ID: xdx_059_edei%2D%2DD...,10-Q,http://www.sec.gov/Archives/edgar/data/1641751...,2022-11-14,2022,528238,https://www.sec.gov/Archives/edgar/data/164175...,5047,10q-bbrw-20220930
16,DQC.US.0099.9533,"2022-11-14 20:17:16,017 [DQC.US.0099.9533] \nT...",2022-11-15,ERROR,DQC,99,1491262,"MEWBOURNE ENERGY PARTNERS 10-A, L.P.",2022-11-14 08:24:00,0001387131-22-011332,US GAAP 2022,Field: Set; Name: xdx; ID: xdx_059_edei%2D%2DD...,10-Q,http://www.sec.gov/Archives/edgar/data/1491262...,2022-11-14,2022,527950,https://www.sec.gov/Archives/edgar/data/149126...,1381,10q-mep-20220930
17,DQC.US.0099.9533,"2022-11-14 20:17:16,017 [DQC.US.0099.9533] \nT...",2022-11-15,ERROR,DQC,99,1491262,"MEWBOURNE ENERGY PARTNERS 10-A, L.P.",2022-11-14 08:24:00,0001387131-22-011332,US GAAP 2022,Field: Set; Name: xdx; ID: xdx_059_edei%2D%2DD...,10-Q,http://www.sec.gov/Archives/edgar/data/1491262...,2022-11-14,2022,527950,https://www.sec.gov/Archives/edgar/data/149126...,1381,10q-mep-20220930
18,DQC.US.0099.9533,"2022-11-14 18:32:12,351 [DQC.US.0099.9533] \nT...",2022-11-14,ERROR,DQC,99,1917993,GROWTH STALK HOLDINGS CORP.,2022-11-14 06:07:00,0001829126-22-019182,US GAAP 2022,Field: Set; Name: xdx; ID: xdx_058_edei%2D%2DD...,10-Q,http://www.sec.gov/Archives/edgar/data/1917993...,2022-11-14,2022,527718,https://www.sec.gov/Archives/edgar/data/191799...,100,10q-cik0001917993-20220630
19,DQC.US.0099.9533,"2023-01-17 17:00:30,319 [DQC.US.0099.9533] \nT...",2023-01-17,ERROR,DQC,99,1605331,AB International Group Corp.,2023-01-17 16:19:00,0001663577-23-000014,US GAAP 2022,Novaworks,10-Q,http://www.sec.gov/Archives/edgar/data/1605331...,2023-01-17,2023,541054,https://www.sec.gov/Archives/edgar/data/160533...,6794,10q-abqq-20221130
20,DQC.US.0099.9533,"2023-01-18 06:45:40,658 [DQC.US.0099.9533] \nT...",2023-01-18,ERROR,DQC,99,91668,"Solitron Devices, Inc.",2023-01-17 17:53:00,0001654954-23-000512,US GAAP 2022,XBRL Document Created with XBRLMaster,10-Q,http://www.sec.gov/Archives/edgar/data/91668/0...,2023-01-18,2023,541156,https://www.sec.gov/Archives/edgar/data/91668/...,3674,10q-sodi-20221130
21,DQC.US.0099.9533,"2023-02-02 19:01:53,630 [DQC.US.0099.9533] \nT...",2023-02-03,ERROR,DQC,99,1604778,"Qorvo, Inc.",2023-02-02 16:10:00,0001604778-23-000034,US GAAP 2022,XBRL Document Created with Wdesk from Workiva,10-Q,http://www.sec.gov/Archives/edgar/data/1604778...,2023-02-02,2023,545306,https://www.sec.gov/Archives/edgar/data/160477...,3674,10q-rfmd-20221231
22,DQC.US.0099.9533,"2023-02-02 19:01:53,630 [DQC.US.0099.9533] \nT...",2023-02-03,ERROR,DQC,99,1604778,"Qorvo, Inc.",2023-02-02 16:10:00,0001604778-23-000034,US GAAP 2022,XBRL Document Created with Wdesk from Workiva,10-Q,http://www.sec.gov/Archives/edgar/data/1604778...,2023-02-02,2023,545306,https://www.sec.gov/Archives/edgar/data/160477...,3674,10q-rfmd-20221231
23,DQC.US.0099.9533,"2023-02-02 19:01:53,630 [DQC.US.0099.9533] \nT...",2023-02-03,ERROR,DQC,99,1604778,"Qorvo, Inc.",2023-02-02 16:10:00,0001604778-23-000034,US GAAP 2022,XBRL Document Created with Wdesk from Workiva,10-Q,http://www.sec.gov/Archives/edgar/data/1604778...,2023-02-02,2023,545306,https://www.sec.gov/Archives/edgar/data/160477...,3674,10q-rfmd-20221231
24,DQC.US.0099.9533,"2023-02-14 15:32:06,985 [DQC.US.0099.9533] \nT...",2023-02-14,ERROR,DQC,99,1616741,"PATRIOT\nTRANSPORTATION HOLDING, INC.",2023-02-14 15:08:00,0001616741-23-000019,US GAAP 2022,Novaworks,10-Q,http://www.sec.gov/Archives/edgar/data/1616741...,2023-02-14,2023,548259,https://www.sec.gov/Archives/edgar/data/161674...,4210,10q-pati-20221231
25,DQC.US.0099.9533,"2023-02-14 17:22:07,841 [DQC.US.0099.9533] \nT...",2023-02-14,ERROR,DQC,99,1791325,Freedom Internet Group Inc.,2023-02-14 16:25:00,0001096906-23-000384,US GAAP 2022,"Produced by EDGARsuite software, Advanced Comp...",10-K,http://www.sec.gov/Archives/edgar/data/1791325...,2023-02-14,2023,548378,https://www.sec.gov/Archives/edgar/data/179132...,6794,10k-figi-20221031
26,DQC.US.0099.9533,"2023-02-23 15:34:42,815 [DQC.US.0099.9533] \nT...",2023-02-23,ERROR,DQC,99,1065696,LKQ CORPORATION,2023-02-23 15:08:00,0001065696-23-000008,US GAAP 2021,XBRL Document Created with Wdesk from Workiva,10-K,http://www.sec.gov/Archives/edgar/data/1065696...,2023-02-23,2023,551270,https://www.sec.gov/Archives/edgar/data/106569...,5010,10k-lkq-20221231
27,DQC.US.0099.9533,"2023-03-01 10:04:18,126 [DQC.US.0099.9533] \nT...",2023-03-01,ERROR,DQC,99,1528930,"Franchise Group, Inc.",2023-02-28 16:13:00,0001528930-23-000005,US GAAP 2022,XBRL Document Created with Wdesk from Workiva,10-K,http://www.sec.gov/Archives/edgar/data/1528930...,2023-02-28,2023,553409,https://www.sec.gov/Archives/edgar/data/152893...,6794,10k-tax-20221231
28,DQC.US.0099.9533,"2023-12-12 22:04:07,575 [DQC.US.0099.9533] \nT...",2023-12-13,ERROR,DQC,99,1616741,"PATRIOT\nTRANSPORTATION HOLDING, INC.",2023-12-12 15:49:00,0001616741-23-000042,US GAAP 2023,Novaworks,10-K,http://www.sec.gov/Archives/edgar/data/1616741...,2023-12-12,2023,661477,https://www.sec.gov/Archives/edgar/data/161674...,4210,10k-pati-20230930
29,DQC.US.0099.9533,"2023-11-29 16:33:06,562 [DQC.US.0099.9533] \nT...",2023-11-29,ERROR,DQC,99,1605331,AB International Group Corp.,2023-11-29 15:35:00,0001663577-23-000552,US GAAP 2023,Novaworks,10-K,http://www.sec.gov/Archives/edgar/data/1605331...,2023-11-29,2023,658506,https://www.sec.gov/Archives/edgar/data/160533...,6794,10k-abqq-20230831
30,DQC.US.0099.9533,"2023-11-14 21:31:59,721 [DQC.US.0099.9533] \nT...",2023-11-15,ERROR,DQC,99,1507957,IDEAL POWER INC.,2023-11-14 16:01:00,0001437749-23-031954,US GAAP 2023,Generated by ThunderDome XBRL - 12:02AM UTC 20...,10-Q,http://www.sec.gov/Archives/edgar/data/1507957...,2023-11-14,2023,654845,https://www.sec.gov/Archives/edgar/data/150795...,3674,10q-ipwr-20230930
31,DQC.US.0099.9533,"2023-11-10 07:01:35,944 [DQC.US.0099.9533] \nT...",2023-11-10,ERROR,DQC,99,894081,"Air Transport Services Group, Inc.",2023-11-09 17:19:00,0000894081-23-000213,US GAAP 2023,XBRL Document Created with the Workiva Platform,10-Q,http://www.sec.gov/Archives/edgar/data/894081/...,2023-11-09,2023,652917,https://www.sec.gov/Archives/edgar/data/894081...,4513,10q-atsg-20230930
32,DQC.US.0099.9533,"2024-01-12 13:01:42,953 [DQC.US.0099.9533] \nT...",2024-01-12,ERROR,DQC,99,1464865,"Accredited Solutions, Inc.",2024-01-12 12:35:00,0001477932-24-000145,US GAAP 2023,XBRL Document Created with XBRLMaster,10-Q,http://www.sec.gov/Archives/edgar/data/1464865...,2024-01-12,2024,667273,https://www.sec.gov/Archives/edgar/data/146486...,2080,10q-accredited-20230930
33,DQC.US.0099.9533,"2024-01-16 16:16:54,493 [DQC.US.0099.9533] \nT...",2024-01-16,ERROR,DQC,99,1575295,Allied Corp.,2024-01-16 15:41:00,0001477932-24-000188,US GAAP 2023,XBRL Document Created with XBRLMaster,10-Q,http://www.sec.gov/Archives/edgar/data/1575295...,2024-01-16,2024,667604,https://www.sec.gov/Archives/edgar/data/157529...,5961,10q-alid-20231130
34,DQC.US.0099.9533,"2024-02-29 21:34:15,479 [DQC.US.0099.9533] \nT...",2024-03-01,ERROR,DQC,99,1411342,ELLINGTON FINANCIAL INC,2024-02-29 16:42:00,0001411342-24-000021,US GAAP 2023,XBRL Document Created with the Workiva Platform,10-K,http://www.sec.gov/Archives/edgar/data/1411342...,2024-02-29,2024,681343,https://www.sec.gov/Archives/edgar/data/141134...,6500,10k-efc-20231231
35,DQC.US.0099.9533,"2024-02-29 21:34:15,479 [DQC.US.0099.9533] \nT...",2024-03-01,ERROR,DQC,99,1411342,ELLINGTON FINANCIAL INC,2024-02-29 16:42:00,0001411342-24-000021,US GAAP 2023,XBRL Document Created with the Workiva Platform,10-K,http://www.sec.gov/Archives/edgar/data/1411342...,2024-02-29,2024,681343,https://www.sec.gov/Archives/edgar/data/141134...,6500,10k-efc-20231231
36,DQC.US.0099.9533,"2024-03-26 11:19:44,533 [DQC.US.0099.9533] \nT...",2024-03-26,ERROR,DQC,99,1319643,"Lode-Star Mining, Inc.",2024-03-22 15:06:00,0001199835-24-000120,US GAAP 2023,Novaworks,10-K,http://www.sec.gov/Archives/edgar/data/1319643...,2024-03-22,2024,692753,https://www.sec.gov/Archives/edgar/data/131964...,1040,10k-lsmg-20231231
37,DQC.US.0099.9533,"2024-04-11 12:16:53,526 [DQC.US.0099.9533] \nT...",2024-04-11,ERROR,DQC,99,838875,WILLAMETTE VALLEY VINEYARDS INC,2024-03-26 16:23:00,0001199835-24-000132,US GAAP 2023,Novaworks,10-K,http://www.sec.gov/Archives/edgar/data/838875/...,2024-03-26,2024,697400,https://www.sec.gov/Archives/edgar/data/838875...,2080,10k-wvvi-20231231
38,DQC.US.0099.9533,"2024-04-02 06:22:11,659 [DQC.US.0099.9533] \nT...",2024-04-02,ERROR,DQC,99,1084133,REAL BRANDS INC.,2024-04-01 16:48:00,0001264931-24-000007,US GAAP 2023,Novaworks,10-K,http://www.sec.gov/Archives/edgar/data/1084133...,2024-04-01,2024,694992,https://www.sec.gov/Archives/edgar/data/108413...,2080,10k-rlbd-20231231
39,DQC.US.0099.9533,"2024-04-02 06:22:11,659 [DQC.US.0099.9533] \nT...",2024-04-02,ERROR,DQC,99,1084133,REAL BRANDS INC.,2024-04-01 16:48:00,0001264931-24-000007,US GAAP 2023,Novaworks,10-K,http://www.sec.gov/Archives/edgar/data/1084133...,2024-04-01,2024,694992,https://www.sec.gov/Archives/edgar/data/108413...,2080,10k-rlbd-20231231
40,DQC.US.0099.9533,"2024-04-02 06:22:11,660 [DQC.US.0099.9533] \nT...",2024-04-02,ERROR,DQC,99,1084133,REAL BRANDS INC.,2024-04-01 16:48:00,0001264931-24-000007,US GAAP 2023,Novaworks,10-K,http://www.sec.gov/Archives/edgar/data/1084133...,2024-04-01,2024,694992,https://www.sec.gov/Archives/edgar/data/108413...,2080,10k-rlbd-20231231
41,DQC.US.0099.9533,"2024-11-18 16:00:52,835 [DQC.US.0099.9533] \nT...",2024-11-18,ERROR,DQC,99,1319643,"Lode-Star Mining, Inc.",2024-11-15 12:34:00,0001199835-24-000512,US GAAP 2024,Novaworks,10-Q,http://www.sec.gov/Archives/edgar/data/1319643...,2024-11-15,2024,781414,https://www.sec.gov/Archives/edgar/data/131964...,1040,10q-lsmg-20240930
42,DQC.US.0099.9533,"2024-11-15 06:36:09,129 [DQC.US.0099.9533] \nT...",2024-11-15,ERROR,DQC,99,838875,WILLAMETTE VALLEY VINEYARDS INC,2024-11-12 16:30:00,0001199835-24-000492,US GAAP 2024,Novaworks,10-Q,http://www.sec.gov/Archives/edgar/data/838875/...,2024-11-12,2024,779429,https://www.sec.gov/Archives/edgar/data/838875...,2080,10q-wvvi-20240930
43,DQC.US.0099.9533,"2024-11-15 10:17:04,302 [DQC.US.0099.9533] \nT...",2024-11-15,ERROR,DQC,99,1411342,ELLINGTON FINANCIAL INC,2024-11-12 15:47:00,0001411342-24-000113,US GAAP 2023,XBRL Document Created with the Workiva Platform,10-Q,http://www.sec.gov/Archives/edgar/data/1411342...,2024-11-12,2024,779538,https://www.sec.gov/Archives/edgar/data/141134...,6500,10q-efc-20240930
44,DQC.US.0099.9533,"2024-11-08 10:31:10,231 [DQC.US.0099.9533] \nT...",2024-11-08,ERROR,DQC,99,55242,KENNAMETAL INC.,2024-11-06 15:18:00,0000055242-24-000067,US GAAP 2024,XBRL Document Created with the Workiva Platform,10-Q,http://www.sec.gov/Archives/edgar/data/55242/0...,2024-11-06,2024,776222,https://www.sec.gov/Archives/edgar/data/55242/...,3541,10q-kmt-20240930
45,DQC.US.0099.9533,"2024-08-26 22:32:12,912 [DQC.US.0099.9533] \nT...",2024-08-27,ERROR,DQC,99,1464865,"Accredited Solutions, Inc.",2024-08-23 06:36:00,0001477932-24-005218,US GAAP 2024,XBRL Document Created with XBRLMaster,10-Q,http://www.sec.gov/Archives/edgar/data/1464865...,2024-08-23,2024,753546,https://www.sec.gov/Archives/edgar/data/146486...,2080,10q-asii-20240630
46,DQC.US.0099.9533,"2024-08-21 06:23:45,365 [DQC.US.0099.9533] \nT...",2024-08-21,ERROR,DQC,99,838875,WILLAMETTE VALLEY VINEYARDS INC,2024-08-13 16:31:00,0001199835-24-000317,US GAAP 2024,Novaworks,10-Q,http://www.sec.gov/Archives/edgar/data/838875/...,2024-08-13,2024,751812,https://www.sec.gov/Archives/edgar/data/838875...,2080,10q-wvvi-20240630
47,DQC.US.0099.9533,"2024-08-14 06:24:10,678 [DQC.US.0099.9533] \nT...",2024-08-14,ERROR,DQC,99,1319643,"Lode-Star Mining, Inc.",2024-08-09 18:24:00,0001199835-24-000296,US GAAP 2024,Novaworks,10-Q,http://www.sec.gov/Archives/edgar/data/1319643...,2024-08-12,2024,749635,https://www.sec.gov/Archives/edgar/data/131964...,1040,10q-lsmg-20240630
48,DQC.US.0099.9533,"2024-08-14 06:08:49,558 [DQC.US.0099.9533] \nT...",2024-08-14,ERROR,DQC,99,1411342,ELLINGTON FINANCIAL INC,2024-08-09 15:35:00,0001411342-24-000078,US GAAP 2023,XBRL Document Created with the Workiva Platform,10-Q,http://www.sec.gov/Archives/edgar/data/1411342...,2024-08-09,2024,749558,https://www.sec.gov/Archives/edgar/data/141134...,6500,10q-efc-20240630
49,DQC.US.0099.9533,"2024-07-16 14:48:15,491 [DQC.US.0099.9533] \nT...",2024-07-16,ERROR,DQC,99,1464865,"Accredited Solutions, Inc.",2024-07-16 14:10:00,0001477932-24-004249,US GAAP 2024,XBRL Document Created with XBRLMaster,10-Q,http://www.sec.gov/Archives/edgar/data/1464865...,2024-07-16,2024,739577,https://www.sec.gov/Archives/edgar/data/146486...,2080,10q-accredited-20240331
50,DQC.US.0099.9533,"2024-07-16 13:18:11,542 [DQC.US.0099.9533] \nT...",2024-07-16,ERROR,DQC,99,1464865,"Accredited Solutions, Inc.",2024-07-16 12:35:00,0001477932-24-004240,US GAAP 2024,XBRL Document Created with XBRLMaster,10-K,http://www.sec.gov/Archives/edgar/data/1464865...,2024-07-16,2024,739561,https://www.sec.gov/Archives/edgar/data/146486...,2080,10k-accredited-20231231

## LLM judge assisstant

In [9]:
Client = OpenAI()

In [11]:
sm_99_system_prompt = """You are given a DQC validation message. Your task is to extract two specific pieces of information:

1. **Statement Name**: Extract the name of the financial statement mentioned in the message. If it appears in a phrase like "0000007 - Statement - Consolidated Statements of Operations", ignore any prefixes such as "- Statement -" or ID numbers. Only return the clean name of the statement (e.g., "Consolidated Statements of Operations").

2. **Erroneous us-gaap Tag(s)**: From all `us-gaap:` prefixed tags mentioned in the message, extract only those that are clearly described as having an error or violation. A tag should be included **only if** it satisfies both of the following:
   - It is explicitly stated to be **not included in any calculation relationship**.
   - The message states that it **will produce an error**, **violates a rule**, or **should have been reported differently**.
Do not include `us-gaap:` tags that are merely suggested, referenced as valid abstract parents, or shown as examples for correction.

3. **Reasoning**: For each extracted erroneous tag, provide a short explanation summarizing why it was classified as erroneous, based on the message.

Output your result as a structured JSON in the following format:
```json
{
  "statement_name": "...",
  "error_tags": [
    {
      "tag": "...",
      "reason": "..."
    }
  ]
}
"""

In [12]:
def get_response(dqc_message):
    
    completion = Client.chat.completions.create(
        model="gpt-4.1-mini",
        response_format={
            "type": "json_object"
        },
        messages=[
            {"role": "system", "content": sm_99_system_prompt},
            {"role": "user", "content": f"DQC validation message: {dqc_message} \n Output:"}
        ]
    )
    return completion.choices[0].message.content

In [13]:
res = []
for _, row in tqdm(sm_99_df.iterrows()):
    ## load each dqc message
    message = row["assertion.detail"]
    response = get_response(message)
    response = json.loads(response)

    ## load the folder name which will be used to obtain candidate segmentation folders
    folder_name = row["folder_name"]

    ## covert the extracted statement name in the message to PascalCase format as the segmentation name
    segmentation_name = to_pascal_case(response.get("statement_name"))

    ## record the folder name
    response["folder_name"] = folder_name
    ## record the extracted segmenataion name
    response["segmentation_name"] = segmentation_name
    res.append(response)

0it [00:00, ?it/s]

51it [02:22,  2.79s/it]

In [14]:
res[0]

{'statement_name': 'CONDENSED BALANCE SHEETS',
 'error_tags': [{'tag': 'us-gaap:PreferredStockValue',
   'reason': 'The tag is included in the presentation but not in any calculation relationship, which will produce an error.'}],
 'folder_name': '10q-anvi-20211130',
 'segmentation_name': 'CondensedBalanceSheets'}

In [15]:
"""
    the options of task_name are semantic_matching, relationship_extraction, and mathematical_reasoning
"""
new_sm_99_df = construct_annotation(sm_99_df, res, task_name="semantic_matching")

In [21]:
new_sm_99_df

,assertion.code,assertion.detail,assertion.run-date,assertion.severity,assertion.source,assertion.type,entity.cik,entity.name,report.accepted-timestamp,report.accession,...,calculation,definition,label,instance,us_gaap,input,true_answer,segmentation_path,parse_successful,LLM_Output
0,DQC.US.0099.9533,"2022-01-03 11:15:38,239 [DQC.US.0099.9533] \nT...",2022-01-03,ERROR,DQC,99,1570132,"ANVI GLOBAL HOLDINGS, INC.",2022-01-03 10:40:00,0001553350-22-000002,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[us-gaap:PreferredStockValue],10q-anvi-20211130/CondensedBalanceSheets,True,"{'statement_name': 'CONDENSED BALANCE SHEETS',..."
1,DQC.US.0099.9533,"2022-01-18 07:01:54,632 [DQC.US.0099.9533] \nT...",2022-01-18,ERROR,DQC,99,1796949,"GenFlat Holdings, Inc.",2022-01-18 06:02:00,0001654954-22-000549,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[],10q-hbr-20211130/ConsolidatedStatementsOfOpera...,True,{'statement_name': 'Consolidated Statements of...
2,DQC.US.0099.9533,"2022-01-18 07:01:54,632 [DQC.US.0099.9533] \nT...",2022-01-18,ERROR,DQC,99,1796949,"GenFlat Holdings, Inc.",2022-01-18 06:02:00,0001654954-22-000549,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,"[us-gaap:ProceedsFromNotesPayable, us-gaap:Pro...",10q-hbr-20211130/ConsolidatedStatementsOfCashF...,True,{'statement_name': 'Consolidated Statements of...
3,DQC.US.0099.9533,"2022-03-09 20:16:45,117 [DQC.US.0099.9533] \nT...",2022-03-10,ERROR,DQC,99,1304161,"PHARMA-BIO SERV, INC.",2022-02-11 17:21:00,0001654954-22-001532,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[us-gaap:OtherComprehensiveIncomeForeignCurren...,10k-pbsv-20211031/ConsolidatedStatementsOfComp...,True,{'statement_name': 'Consolidated Statements of...
4,DQC.US.0099.9533,"2022-02-15 07:30:54,506 [DQC.US.0099.9533] \nT...",2022-02-15,ERROR,DQC,99,1620749,PANAMERA HOLDINGS CORPORATION,2022-02-14 21:51:00,0001640334-22-000315,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,"[us-gaap:LiabilitiesAndStockholdersEquity, us-...",10k-pnht-20210731/BalanceSheets,True,"{'statement_name': 'Balance Sheets', 'error_ta..."
5,DQC.US.0099.9533,"2022-02-15 07:30:54,507 [DQC.US.0099.9533] \nT...",2022-02-15,ERROR,DQC,99,1620749,PANAMERA HOLDINGS CORPORATION,2022-02-14 21:51:00,0001640334-22-000315,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[us-gaap:CashAndCashEquivalentsPeriodIncreaseD...,10k-pnht-20210731/StatementsOfCashFlowsUnaudited,True,{'statement_name': 'Statements of Cash Flows (...
6,DQC.US.0099.9533,"2022-02-18 09:45:49,004 [DQC.US.0099.9533] \nT...",2022-02-18,ERROR,DQC,99,1602813,FRONTERA GROUP INC.,2022-02-18 09:24:00,0001549727-22-000009,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,None,None,None,[us-gaap:IncreaseDecreaseInAccountsPayableAndA...,10q-frtg-20211231/StatementsOfCashFlows,True,{'statement_name': 'STATEMENTS OF CASH FLOWS (...
7,DQC.US.0099.9533,"2022-12-19 12:02:34,485 [DQC.US.0099.9533] \nT...",2022-12-19,ERROR,DQC,99,1230524,"Leopard Energy, Inc.",2022-12-14 16:20:00,0001903596-22-000915,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[us-gaap:ProceedsFromIssuanceOfPreferredStockA...,10q-cetc-20221031/StatementOfCashFlows,True,{'statement_name': 'Consolidated Statement of ...
8,DQC.US.0099.9533,"2022-11-23 06:02:44,800 [DQC.US.0099.9533] \nT...",2022-11-23,ERROR,DQC,99,1602813,FRONTERA GROUP INC.,2022-11-22 15:10:00,0001549727-22-000096,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[us-gaap:IncreaseDecreaseInAccountsPayableAndA...,10q-frtg-20220930/StatementsOfCashFlows,True,{'statement_name': 'STATEMENTS OF CASH FLOWS (...
9,DQC.US.0099.9533,"2022-11-17 06:28:43,249 [DQC.US.0099.9533] \nT...",2022-11-17,ERROR,DQC,99,1876945,Gold Flora Corporation,2022-11-14 16:56:00,0001654954-22-015300,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[us-gaap:CommonStockValue],10q-gramf-20220930/InterimCondensedConsolidate...,True,{'statement_name': 'Interim Condensed Consolid...
10,DQC.US.0099.9533,"2022-11-17 06:28:43,249 [DQC.US.0099.9533] \nT...",2022-11-17,ERROR,DQC,99,1876945,Gold Flora Corporation,2022-11-14 16:56:00,0001654954-22-015300,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[gramf:LossAndComprehensiveLossAttributableToS...,10q-gramf-20220930/InterimCondensedConsolidate...,True,{'statement_name': 'Interim condensed consolid...
11,DQC.US.0099.9533,"2022-11-17 06:28:43,249 [DQC.US.0099.9533] \nT...",2022-11-17,ERROR,DQC,99,1876945,Gold Flora Corporation,2022-11-14 16:56:00,0001654954-22-015300,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[],10q-gramf-20220930/InterimCondensedConsolidate...,True,{'statement_name': 'Interim Condensed Consolid...
12,DQC.US.0099.9533,"2022-11-15 07:58:34,662 [DQC.US.0099.9533] \nT...",2022-11-15,ERROR,DQC,99,1471781,GBT TECHNOLOGIES INC.,2022-11-14 16:17:00,0001731122-22-001969,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[us-gaap:PreferredStockValue],10q-gtch-20220930/CondensedConsolidatedBalance...,True,{'statement_name': 'CONDENSED CONSOLIDATED BAL...
13,DQC.US.0099.9533,"2022-11-15 07:58:34,662 [DQC.US.0099.9533] \nT...",2022-11-15,ERROR,DQC,99,1471781,GBT TECHNOLOGIES INC.,2022-11-14 16:17:00,0001731122-22-001969,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[us-gaap:IncomeLossFromContinuingOperations],10q-gtch-20220930/CondensedConsolidatedStateme...,True,{'statement_name': 'CONDENSED CONSOLIDATED STA...
14,DQC.US.0099.9533,"2022-11-15 07:58:34,662 [DQC.US.0099.9533] \nT...",2022-11-15,ERROR,DQC,99,1471781,GBT TECHNOLOGIES INC.,2022-11-14 16:17:00,0001731122-22-001969,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[],10q-gtch-20220930/CondensedConsolidatedStateme...,True,{'statement_name': 'CONDENSED CONSOLIDATED STA...
15,DQC.US.0099.9533,"2022-11-15 06:36:01,493 [DQC.US.0099.9533] \nT...",2022-11-15,ERROR,DQC,99,1641751,BrewBilt Manufacturing Inc.,2022-11-14 13:32:00,0001641751-22-000018,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,"[us-gaap:IncreaseDecreaseInAccountsReceivable,...",10q-bbrw-20220930/ConsolidatedStatementsOfCash...,True,{'statement_name': 'CONSOLIDATED STATEMENTS OF...
16,DQC.US.0099.9533,"2022-11-14 20:17:16,017 [DQC.US.0099.9533] \nT...",2022-11-15,ERROR,DQC,99,1491262,"MEWBOURNE ENERGY PARTNERS 10-A, L.P.",2022-11-14 08:24:00,0001387131-22-011332,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[us-gaap:RevenueFromContractWithCustomerInclud...,10q-mep-20220930/CondensedStatementsOfOperations,True,{'statement_name': 'CONDENSED STATEMENTS OF OP...
17,DQC.US.0099.9533,"2022-11-14 20:17:16,017 [DQC.US.0099.9533] \nT...",2022-11-15,ERROR,DQC,99,1491262,"MEWBOURNE ENERGY PARTNERS 10-A, L.P.",2022-11-14 08:24:00,0001387131-22-011332,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[mep:OilAndGasPropertyAdditionsIncludedInAccou...,10q-mep-20220930/CondensedStatementsOfCashFlows,True,{'statement_name': 'CONDENSED STATEMENTS OF CA...
18,DQC.US.0099.9533,"2022-11-14 18:32:12,351 [DQC.US.0099.9533] \nT...",2022-11-14,ERROR,DQC,99,1917993,GROWTH STALK HOLDINGS CORP.,2022-11-14 06:07:00,0001829126-22-019182,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[us-gaap:PreferredStockValue],10q-cik0001917993-20220630/CondensedConsolidat...,True,{'statement_name': 'CONDENSED CONSOLIDATED BAL...
19,DQC.US.0099.9533,"2023-01-17 17:00:30,319 [DQC.US.0099.9533] \nT...",2023-01-17,ERROR,DQC,99,1605331,AB International Group Corp.,2023-01-17 16:19:00,0001663577-23-000014,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[us-gaap:PaymentsOfDividendsPreferredStockAndP...,10q-abqq-20221130/StatementsOfOperations,True,{'statement_name': 'Consolidated Statements of...
20,DQC.US.0099.9533,"2023-01-18 06:45:40,658 [DQC.US.0099.9533] \nT...",2023-01-18,ERROR,DQC,99,91668,"Solitron Devices, Inc.",2023-01-17 17:53:00,0001654954-23-000512,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[sodi:ReclassificationOfConstructionInProgress...,10q-sodi-20221130/StatementsOfCashFlowsUnaudited,True,{'statement_name': 'STATEMENTS OF CASH FLOWS (...
21,DQC.US.0099.9533,"2023-02-02 19:01:53,630 [DQC.US.0099.9533] \nT...",2023-02-03,ERROR,DQC,99,1604778,"Qorvo, Inc.",2023-02-02 16:10:00,0001604778-23-000034,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[us-gaap:GoodwillPurchaseAccountingAdjustments],10q-rfmd-20221231/CondensedConsolidatedStateme...,True,{'statement_name': 'Condensed Consolidated Sta...
22,DQC.US.0099.9533,"2023-02-02 19:01:53,630 [DQC.US.0099.9533] \nT...",2023-02-03,ERROR,DQC,99,1604778,"Qorvo, Inc.",2023-02-02 16:10:00,0001604778-23-000034,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[us-gaap:OtherComprehensiveIncomeLossForeignCu...,10q-rfmd-20221231/CondensedConsolidatedStateme...,True,{'statement_name': 'Condensed Consolidated Sta...
23,DQC.US.0099.9533,"2023-02-02 19:01:53,630 [DQC.US.0099.9533] \nT...",2023-02-03,ERROR,DQC,99,1604778,"Qorvo, Inc.",2023-02-02 16:10:00,0001604778-23-000034,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,"[us-gaap:RepaymentsOfLongTermDebt, us-gaap:Pro...",10q-rfmd-20221231/CondensedConsolidatedStateme...,True,{'statement_name': 'Condensed Consolidated Sta...
24,DQC.US.0099.9533,"2023-02-14 15:32:06,985 [DQC.US.0099.9533] \nT...",2023-02-14,ERROR,DQC,99,1616741,"PATRIOT\nTRANSPORTATION HOLDING, INC.",2023-02-14 15:08:00,0001616741-23-000019,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[us-gaap:RightOfUseAssetObtainedInExchangeForO...,10q-pati-20221231/ConsolidatedStatementsOfCash...,True,{'statement_name': 'CONSOLIDATED STATEMENTS OF...
25,DQC.US.0099.9533,"2023-02-14 17:22:07,841 [DQC.US.0099.9533] \nT...",2023-02-14,ERROR,DQC,99,1791325,Freedom Internet Group Inc.,2023-02-14 16:25:00,0001096906-23-000384,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<linkb...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[us-gaap:NetCashProvidedByUsedInFinancingActiv...,10k-figi-20221031/idr_StatementConsolidatedSta...,True,{'statement_name': 'Consolidated Statements of...
26,DQC.US.0099.9533,"2023-02-23 15:34:42,815 [DQC.US.0099.9533] \nT...",2023-02-23,ERROR,DQC,99,1065696,LKQ CORPORATION,2023-02-23 15:08:00,0001065696-23-000008,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[us-gaap:ProceedsFromIssuanceOfDebt],10k-lkq-20221231/ConsolidatedStatementsofCashF...,True,{'statement_name': 'Consolidated Statements of...
27,DQC.US.0099.9533,"2023-03-01 10:04:18,126 [DQC.US.0099.9533] \nT...",2023-03-01,ERROR,DQC,99,1528930,"Franchise Group, Inc.",2023-02-28 16:13:00,0001528930-23-000005,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[tax:SecuritizedReceivablesNetCurrent],10k-tax-20221231/ConsolidatedBalanceSheets,True,{'statement_name': 'Consolidated Balance Sheet...
28,DQC.US.0099.9533,"2023-12-12 22:04:07,575 [DQC.US.0099.9533] \nT...",2023-12-13,ERROR,DQC,99,1616741,"PATRIOT\nTRANSPORTATION HOLDING, INC.",2023-12-12 15:49:00,0001616741-23-000042,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[us-gaap:RightOfUseAssetObtainedInExchangeForO...,10k-pati-20230930/ConsolidatedStatementsOfCash...,True,{'statement_name': 'CONSOLIDATED STATEMENTS OF...
29,DQC.US.0099.9533,"2023-11-29 16:33:06,562 [DQC.US.0099.9533] \nT...",2023-11-29,ERROR,DQC,99,1605331,AB International Group Corp.,2023-11-29 15:35:00,0001663577-23-000552,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[us-gaap:PaymentsOfDividendsPreferredStockAndP...,10k-abqq-20230831/StatementsOfOperations,True,{'statement_name': 'Consolidated Statements of...
30,DQC.US.0099.9533,"2023-11-14 21:31:59,721 [DQC.US.0099.9533] \nT...",2023-11-15,ERROR,DQC,99,1507957,IDEAL POWER INC.,2023-11-14 16:01:00,0001437749-23-031954,...,None,None,None,None,None,None,"[us-gaap:OperatingLeaseLiabilityNoncurrent, us...",None,False,{'statement_name': 'Balance Sheets (Unaudited)...
31,DQC.US.0099.9533,"2023-11-10 07:01:35,944 [DQC.US.0099.9533] \nT...",2023-11-10,ERROR,DQC,99,894081,"Air Transport Services Group, Inc.",2023-11-09 17:19:00,0000894081-23-000213,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[us-gaap:ProceedsFromPaymentsForOtherFinancing...,10q-atsg-20230930/CONSOLIDATEDSTATEMENTSOFCASH...,True,{'statement_name': 'CONSOLIDATED STATEMENTS OF...
32,DQC.US.0099.9533,"2024-01-12 13:01:42,953 [DQC.US.0099.9533] \nT...",2024-01-12,ERROR,DQC,99,1464865,"Accredited Solutions, Inc.",2024-01-12 12:35:00,0001477932-24-000145,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[us-gaap:NetCashProvidedByUsedInContinuingOper...,10q-accredited-20230930/CondensedConsolidatedS...,True,{'statement_name': 'CONDENSED CONSOLIDATED STA...
33,DQC.US.0099.9533,"2024-01-16 16:16:54,493 [DQC.US.0099.9533] \nT...",2024-01-16,ERROR,DQC,99,1575295,Allied Corp.,2024-01-16 15:41:00,0001477932-24-000188,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,[alid:AdjustmentForAccruedInterest],10q-alid-20231130/CondensedConsolidatedInterim...,True,{'statement_name': 'Condensed Consolidated Int...
34,DQC.US.0099.9533,"2024-02-29 21:34:15,479 [DQC.US.0099.9533] \nT...",2024-03-01,ERROR,DQC,99,1411342,ELLINGTON FINANCIAL INC,2024-02-29 16:42:00,0001411342-24-000021,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,"[efc:ForwardMSRRelatedInvestmentsAtFairValue, ...",10k-efc-20231231/ConsolidatedBalanceSheet,True,{'statement_name': 'Consolidated Balance Sheet...
35,DQC.US.0099.9533,"2024-02-29 21:34:15,479 [DQC.US.0099.9533] \nT...",2024-03-01,ERROR,DQC,99,1411342,ELLINGTON FINANCIAL INC,2024-02-29 16:42:00,0001411342-24-000021,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,"[us-gaap:AmortizationOfFinancingCosts, us-gaap...",10k-efc-20231231/ConsolidatedStatementofCashFlows,True,{'statement_name': 'Consolidated Statement of ...
36,DQC.US.0099.9533,"2024-03-26 11:19:44,533 [DQC.US.0099.9533] \nT...",2024-03-26,ERROR,DQC,99,1319643,"Lode-Star Mining, Inc.",2024-03-22 15:06:00,0001199835-24-000120,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,None,None,"[us-gaap:IncreaseDecreaseInPrepaidExpense, us-...",10k-lsmg-20231231/StatementsOfCashFlows,True,"{'statement_name': 'STATEMENTS OF CASH FLOWS',..."

In [20]:
new_sm_99_df.to_excel(output_data,index=False)